config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'

  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users, only: [:create, :index, :show]
  resources :microposts, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user

  validates :content, presence: true, length: { maximum: 255 }
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                   format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                   uniqueness: { case_sensitive: false }

  has_secure_password
  has_many :microposts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :require_user_logged_in
  def create
    @m = Micropost.find(params[:id])
    redirect_back(fallback_location: root_path)
  end
  def destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy]

  def create
    # @m = current_user.microposts.build(set_micropost)
    @m = Micropost.new(set_micropost)
    @m.user_id = current_user.id
    if @m.save
      flash[:success] = "Posts!!!"
      # redirect_back(fallback_location: root_path)
      redirect_to root_url
    else
      @list = Micropost.all
      flash.now[:danger] = "noT Posts!!"
      render 'toppages/index'
    end
  end
  def destroy
    @m.destroy
    redirect_back(fallback_location: root_path)
  end

  private
  def set_micropost
    params.require(:micropost).permit(:content)
  end
  def correct_user
    @m = Micropost.find(params[:id])
    unless @m.user == current_user
      redirect_to root_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      flash[:success] = "ログインしたぜ."
      session[:user_id] = @user.id
      redirect_to root_url
    else
      flash.now[:danger] = "ログインダメだぜ."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "Logout成功."
    redirect_to root_url
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    # @micropost = current_user.microposts.build
    @list = Micropost.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  def new
    @user = User.new
  end
  def create
    @user = User.new(set_user)
    if @user.save
      flash[:success] = "ユーザ登録成功だぜ."
      redirect_to root_url
    else
      flash[:danger] = "おいおい.失敗だぜ."
      render :new
    end
  end
  def index
    @users = User.all
  end
  def show
    @user = User.find(params[:id])
  end

  private
  def set_user
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    unless @current_user
      @current_user = User.find_by(id: session[:user_id])
    else
      @current_user
    end
  end
  def logged_in?
    # !!current_user
    if current_user.nil?
      false
    else
      true
    end
  end
end

app/views/layouts/_error_messages.html.slim
- if model.errors.any?
  .alert.alert-warning
    ul
    - model.errors.full_messages.each do |message|
      li= message

app/views/layouts/_flash_messages.html.slim
- flash.each do |message_type, message|
  .alert[class="alert-#{message_type}"]
    = message

app/views/layouts/_navbar.html.slim
header
  nav.navbar.navbar-inverse.navbar-static-top
    .container
      .navbar-header
        button.navbar-toggle.collapsed aria-expanded="false" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button"
          span.sr-only Toggle navigation
          span.icon-bar
          span.icon-bar
          span.icon-bar
        a.navbar-brand href="/"  Microposts
      #bs-example-navbar-collapse-1.collapse.navbar-collapse
        ul.nav.navbar-nav.navbar-right
          - if logged_in?
            li= link_to 'Users', users_path
            li.dropdown
              a.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
                = current_user.name
                span.caret
              ul.dropdown-menu
                li= link_to 'My profile', user_path(current_user)
                li.divider role="separator"
                li= link_to 'Logout', logout_path, method: :delete
          - else
            li
              = link_to 'Signup', signup_path
            li
              = link_to 'Login', login_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | TwitterClone
    meta charset="utf-8" /
    meta content="IE=edge" http-equiv="X-UA-Compatible" /
    meta content="width=device-width, initial-scale=1" name="viewport" /
    = csrf_meta_tags
    link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" /
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
  body
    = render 'layouts/navbar'
    .container
      = render 'layouts/flash_messages'
      = yield


    = debug(params) if Rails.env.development?

app/views/toppages/index.html.slim
- if logged_in?
  .row
    aside.col-md-4
      = form_for(Micropost.new) do |f|
        .form-group
          = f.text_area :content, class: 'form-control', rows: 5
        = f.submit 'Post', class: 'btn btn-primary btn-block'
    .col-xs-8
      / = render 'microposts/microposts', microposts: @microposts
      - @list.each do |micropost|
        p
          = micropost.content
          span= "(投稿者: #{micropost.user.name})"
          = link_to 'delete', micropost, method: :delete, class: 'btn btn-danger btn-xs'
          = link_to 'favo', "/favorites?id=#{micropost.id}", method: :post, class: 'btn btn-primary btn-xs'

- else
  .center.jumbotron
    .text-center
      h1 Welcome to the Micropost
      = link_to 'Signup', signup_path, class: 'btn btn-primary btn-lg'

app/views/users/index.html.slim
h1 Users
- @users.each do |user|
  p
    = user.name
    = link_to 'profile', user

app/views/users/new.html.slim
.text-center
  h1 Sign up
.row
  .col-md-6.col-md-offset-3
    = form_for(@user) do |f|
      = render 'layouts/error_messages', model: f.object
      .form-group
        = f.label :name, 'Name'
        = f.text_field :name, class: 'form-control'
      .form-group
        = f.label :email, 'Email'
        = f.email_field :email, class: 'form-control'
      .form-group
        = f.label :password, 'Password'
        = f.password_field :password, class: 'form-control'
      .form-group
        = f.label :password_confirmation, 'Confirmation'
        = f.password_field :password_confirmation, class: 'form-control'
      = f.submit 'Sign up', class: 'btn btn-primary btn-block'

app/views/users/show.html.slim
h1 User show

p= @user.name